;;; ==================================================
;;; STATE.scm — AI Conversation Checkpoint File
;;; ==================================================
;;;
;;; SPDX-License-Identifier: MIT AND LicenseRef-Palimpsest-0.8
;;; Copyright (c) 2025 Jonathan D.A. Jewell
;;;
;;; STATEFUL CONTEXT TRACKING ENGINE
;;; Version: 2.0
;;;
;;; CRITICAL: Download this file at end of each session!
;;; At start of next conversation, upload it.
;;; Do NOT rely on ephemeral storage to persist.
;;;
;;; For query functions, load the library:
;;;   (add-to-load-path "/path/to/STATE.djot/lib")
;;;   (use-modules (state))
;;;
;;; ==================================================

(define state
  '((metadata
      (format-version . "2.0")
      (schema-version . "2025-12-06")
      (created-at . "TIMESTAMP")
      (last-updated . "TIMESTAMP")
      (generator . "Claude/STATE-system"))

    (user
      (name . "YOUR NAME")
      (roles . ("role1" "role2"))
      (preferences
        (languages-preferred . ("Rust" "Elixir" "Haskell"))
        (languages-avoid . ())
        (tools-preferred . ("GitLab" "Podman" "Guix"))
        (values . ("FOSS" "reproducibility" "formal-verification"))))

    (session
      (conversation-id . "CONVERSATION-UUID")
      (started-at . "TIMESTAMP")
      (messages-used . 0)
      (messages-remaining . 100)
      (token-limit-reached . #f))

    (focus
      (current-project . "PROJECT-NAME")
      (current-phase . "phase-description")
      (deadline . #f)
      (blocking-projects . ()))

    (projects
      ;; Project template - copy and modify as needed
      ;;
      ;; Status values:
      ;;   in-progress  - actively being worked on
      ;;   blocked      - waiting on dependency or external factor
      ;;   paused       - intentionally on hold
      ;;   complete     - finished
      ;;   abandoned    - no longer pursuing
      ;;
      ;; Category values:
      ;;   language              - programming language design/implementation
      ;;   ai                    - artificial intelligence projects
      ;;   formal-verification   - proofs, type systems, verification
      ;;   standards             - specifications, protocols, formats
      ;;   infrastructure        - tooling, devops, services
      ;;   education             - courses, curricula, teaching materials

      ((name . "Example Project")
       (status . "in-progress")
       (completion . 0)
       (category . "infrastructure")
       (phase . "planning")
       (dependencies . ())
       (blockers . ())
       (next . ("Define requirements" "Create initial design"))
       (chat-reference . #f)
       (notes . "")))

    (critical-next
      ;; Top 3-5 immediate actions across all projects
      ;; These should be the most time-sensitive or impactful
      ("Action 1 description"
       "Action 2 description"
       "Action 3 description"))

    (history
      ;; Completion history for velocity tracking and time estimation
      ;; Each snapshot records project completion at a point in time
      ;; Used by state-history module for:
      ;;   - Velocity calculation (% per day)
      ;;   - Estimated completion dates
      ;;   - Burndown charts
      (snapshots
        ;; Example snapshot - auto-generated by create-snapshot
        ;; ((timestamp . "2025-12-01T10:00:00Z")
        ;;  (projects
        ;;    ((name . "Example Project") (completion . 0))))
        ))

    (files-created-this-session
      ;; Paths to files created during current conversation
      ())

    (files-modified-this-session
      ;; Paths to files modified during current conversation
      ())

    (context-notes . "Additional context for next session")))

;;; ==================================================
;;; QUICK REFERENCE
;;; ==================================================
;;;
;;; Load the library for full functionality:
;;;
;;;   (add-to-load-path "/path/to/STATE.djot/lib")
;;;   (use-modules (state))
;;;
;;; Core queries:
;;;   (get-current-focus state)      ; Current project name
;;;   (get-blocked-projects state)   ; All blocked projects
;;;   (get-critical-next state)      ; Priority actions
;;;   (should-checkpoint? state)     ; Need to save?
;;;
;;; minikanren queries:
;;;   (run* (q) (statuso q "blocked" state))  ; All blocked
;;;   (run* (q) (dependso "ProjectA" q state)) ; Dependencies
;;;
;;; Visualization:
;;;   (generate-dot state)           ; GraphViz DOT output
;;;   (generate-mermaid state)       ; Mermaid diagram
;;;
;;; Time estimation:
;;;   (project-velocity "Project" state)       ; %/day
;;;   (estimate-completion-date "Project" state) ; ISO date
;;;   (velocity-report state)        ; Print velocity report
;;;   (progress-report state)        ; Print progress report
;;;
;;; History management:
;;;   (create-snapshot state)        ; Create new snapshot
;;;   (add-snapshot-to-history snapshot state) ; Add to history
;;;
;;; ==================================================
;;; END STATE.scm
;;; ==================================================
